### ISSUE TITLE
Support for osx-aarch64 (Apple M1 silicon)

### ISSUE THREAD

**Issue by fkoehler** [lmdbjava/native#10]
In order to run akka cluster on a new apple m1 the native library for it's arch would be required. I am a bit unsure on how to add it.

**Comment by benalexau** [comment]
I thought that new Apples containing M1 Silicon tried to be backward compatible with code compiled for MacOS x64_64. Is that not the case? Did you try it?

If you had access to an LMDB native library that was compiled for M1 Silicon (eg you compiled it yourself or found it elsewhere) you can set the `lmdbjava.native.lib` system property to the location of that library. This system property is read in the [Library](https://github.com/lmdbjava/lmdbjava/blob/master/src/main/java/org/lmdbjava/Library.java) class. Any PRs that improve `Library` to offer better backward compatibility are very welcome.

The longer-term solution is for the LmdbJava Native project to compile for Apple M1 as an explicitly-supported target. However we use GitHub Actions to build the various native libraries and as detailed in [GitHub Actions Issue #2187](https://github.com/actions/virtual-environments/issues/2187) there is currently no support for Apple M1 Silicon in GitHub Actions workflows. It appears [possible](https://github.com/actions/runner/issues/805) to use a self-hosted runner, but I do not have any hardware that would host such a runner.

I will leave this issue open while we wait for the aforementioned GitHub Actions issue to communicate a decision regarding support of M1 Silicon in workflows.

**Comment by savulchik** [comment]
For someone curious how to build the `lmdb` native library on the Apple M1:

1. download the source code from https://git.openldap.org/openldap/openldap/tree/mdb.master
2. in the directory with the Makefile run `make -e SOEXT=.dylib`

To verify:
```sh
$ otool -hv liblmdb.dylib
liblmdb.dylib:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    15       1536   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
```

**Comment by cpdean** [comment]
I'm trying to get this to work with a natively-built lmdb on an Apple M1, but still getting errors that look like they're coming from jffi's ability to use it?  When I set the system property `lmdbjava.native.lib` via the command line, I get identical errors to when I do not:

```
mvn test -Dtest=TutorialTest -Dlmdbjava.native.lib=$(brew --prefix)/lib/liblmdb.dylib

[INFO] Running org.lmdbjava.TutorialTest
[ERROR] Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.071 s <<< FAILURE! - in org.lmdbjava.TutorialTest
[ERROR] tutorial1(org.lmdbjava.TutorialTest)  Time elapsed: 0.042 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:49)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:417)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:396)
        at org.lmdbjava.Library.<clinit>(Library.java:125)
        at org.lmdbjava.Env$Builder.open(Env.java:486)
        at org.lmdbjava.Env$Builder.open(Env.java:512)
        at org.lmdbjava.TutorialTest.tutorial1(TutorialTest.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: Unable to execute
or load jffi binary stub from `/var/folders/bv/prppgdjd1s18w7832bn94kyc0000gn/T/`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexe
c".
/Users/conraddean/dev/foss/java/lmdbjava/jffi10326609349465222448.dylib: dlopen(/Users/conraddean/dev/foss/java/lmdbjava/jffi10326609349465222448.dylib, 0x0001): tried: '/Users/
conraddean/dev/foss/java/lmdbjava/jffi10326609349465222448.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/local/lib/jffi103266
09349465222448.dylib' (no such file), '/usr/lib/jffi10326609349465222448.dylib' (no such file)
        at com.kenai.jffi.internal.StubLoader.tempLoadError(StubLoader.java:448)
        at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:433)
        at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:300)
        at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:511)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.kenai.jffi.Init.load(Init.java:68)
        at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:50)
        at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:46)
        at com.kenai.jffi.Foreign.getInstance(Foreign.java:104)
        at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
        at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
        at com.kenai.jffi.Type.resolveSize(Type.java:155)
        at com.kenai.jffi.Type.size(Type.java:138)
        at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:182)
        at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:61)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:45)
        at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:57)
        at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:53)
        at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
        at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
        at jnr.ffi.LibraryLoader.create(LibraryLoader.java:88)
        at org.lmdbjava.Library.<clinit>(Library.java:125)
        at org.lmdbjava.Env$Builder.open(Env.java:486)
        at org.lmdbjava.Env$Builder.open(Env.java:512)
        at org.lmdbjava.TutorialTest.tutorial1(TutorialTest.java:97)
```

Am I doing that right? or is there something more I need to do to get this to use the lmdb that I have locally?

**Comment by savulchik** [comment]
@cpdean I got the same error when I tried to use the library.. Don't know what to do to resolve the issue, sorry

**Comment by bsergean** [comment]
Maybe the jni library could be built as an arm/aarch binary on an Intel box (the one that github action provide) ?

**Comment by wardle** [comment]
I have lmdbjava 0.8.2 working on Apple silicon:

Build native lmdb binary:
```shell
xcode-select --install
git clone --depth 1 https://git.openldap.org/openldap/openldap.git
cd openldap/libraries/liblmdb
make -e SOEXT=.dylib
mkdir -p ~/Library/Java/Extensions
cp  liblmdb.dylib ~/Library/Java/Extensions
```

The errors listed by others above relate to an old jnr-ffi, so you can fix that by overriding lmdbjava's dependency on com.github.jnr/jnr-ffi to "2.2.12" explicitly in your pom.xml or equivalent. It looks as if lmdbjava 0.8.3-SNAPSHOT has already done this, so this step won't be necessary once that is published to maven, or you run mvn install from source.

**Comment by benalexau** [comment]
Closing this ticket as https://github.com/lmdbjava/lmdbjava/pull/217 has provided a Zig-based cross-compilation in the Java module product and this includes Apple Silicon support.
